wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1649697463
    t:
      1:
      - 5
      - 53
      - 55
      4: 3.9.7
      5: 0.12.14
      8:
      - 1
      - 2
      - 3
      - 5
